### ISSUE TITLE
协议，版权，“参与开发”方面的一些问题

### ISSUE THREAD

**Issue by ouuan** [oitl-5ab/OITL#1]
LICENSE 是 GPL-3.0，README 里写的又是“转载即同意 CC BY-SA 3.0”。CC BY-SA 4.0（不太了解 3.0 和 4.0 的区别）是单向兼容 GPL-3.0 的，所以这实在是非常迷惑..（而且，“转载即同意”这个说法对于 CC BY-SA 3.0 这样的协议来说，也是很奇怪的。其它软件有“使用即同意”，是因为那些协议中规定了双方的权利和义务，比如软件可能会获取你的一些个人信息，相应地，软件也会给你提供服务。而 CC BY-SA 3.0 中不存在这样的问题，如果你不转载，只是阅读协议之下的作品，作者并没有要求你授权给他什么。而转载时，义务都在转载者身上，不是转载者不同意就可以不遵守的。）

建议改用一些更加宽松的协议，如 MIT License，或者 Apache License 2.0。如果使用 GPL-3.0 的话，任何使用这个库的代码都必须在 GPL-3.0 下开源地发布，这在 OI 中使用是非常不方便的（比如，如果在洛谷上使用，就不能开启隐私保护），我想您也没有这样的想法，只是不了解相关协议。至于 CC 系列的协议，一般不用于代码，而用于文章之类的东西。

另外是从自由软件的角度出发，对“参与开发”的一点小建议，您可以自由选择是否采纳：建议不要使用“奖项认证”来作为“参与开发”的条件。其实如果要参与的话，发一个 Pull request 就好了，您是想拒绝没有获奖的人的 Pull requests，而不看其内容吗？我认为这是不符合自由软件的精神的（当然，您除了使用 GPL-3.0 协议外，也没有表示您是自由软件的拥护者，所以还是看您的想法）。当然，您可以对“加入核心开发团队”做出一些要求，这我是没有异议的。另外，将“提 Issue”和“加入开发群”挂钩，我感觉也很奇怪..

还有就是，GitHub 不支持 LaTeX，而且 `[1]` 这种东西本来就不该使用 LaTeX（它不是数学公式）。

**Comment by oitl-5ab** [comment]
不好意思，由于这些东西都是我下瞎编的（滑稽），所以有点错误，感谢指正！


额关于协议，我觉得并没有什么较大的要求。而且开发群那都是远古的事情了，目前为止都是个人在写。


至于LaTeX，可能是某咕的奇怪特性，不知道为什么GitHub 不支持Markdown的注释语法（也有可能是我不会）。


总之，感谢大佬指出本蒟蒻的种种不合理之处。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ouuan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月7日(星期六) 晚上9:39
收件人:&nbsp;"oitl-5ab/OITL"<OITL@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[oitl-5ab/OITL] 协议，版权，“参与开发”方面的一些问题 (#1)




LICENSE 是 GPL-3.0，README 里写的又是“需要遵守 CC BY-SA 3.0”，CC BY-SA 4.0（不太了解 3.0 和 4.0 的区别）是单向兼容 GPL-3.0 的，所以这实在是非常迷惑..
 
建议改用一些更加宽松的协议，如 MIT License，或者 Apache License 2.0。如果使用 GPL-3.0 的话，任何使用这个库的代码都必须在 GPL-3.0 下开源地发布，这在 OI 中使用是非常不方便的（比如，如果在洛谷上使用，就不能开启隐私保护），我想您也没有这样的想法，只是不了解相关协议。至于 CC 系列的协议，一般不用于代码，而用于文章之类的东西。
 
另外是从自由软件的角度出发，对“参与开发”的一点小建议，您可以自由选择是否采纳：建议不要使用“奖项认证”来作为“参与开发”的条件。其实如果要参与的话，发一个 Pull request 就好了，您是想拒绝没有获奖的人的 Pull requests，而不看其内容吗？我认为这是不符合自由软件的精神的（当然，您除了使用 GPL-3.0 协议外，也没有表示您是自由软件的拥护者，所以还是看您的想法）。当然，您可以对“加入核心开发团队”做出一些要求，这我是没有异议的。另外，将“提 Issue”和“加入开发群”挂钩，我感觉也很奇怪..
 
还有就是，GitHub 不支持 LaTeX，而且 [1] 这种东西本来就不该使用 LaTeX（它不是数学公式）。

**Comment by ouuan** [comment]
我相信很多人都是没搞清楚 License 之间的区别及具体作用就开始在 GitHub 上把自己一些东西开源，随便加个协议，就算真的有人违反协议也不会去追究（我自己以前也是这样）。只不过还是严谨一点好。如果你不想给自己的代码加太多限制，MIT License 是最宽松的，只要使用者提一句“我用的这个东西是在 MIT License 下发布的”，没有其它任何限制。

https://www.gnu.org/licenses/license-list.html 比较详细地列出了很多 License。

**Comment by oitl-5ab** [comment]
谢谢大佬指出！本蒟蒻会尽力改进的。（虽然窝很好奇为什么GitHub不支持 CC-BY SA 系列）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ouuan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月7日(星期六) 晚上9:47
收件人:&nbsp;"oitl-5ab/OITL"<OITL@noreply.github.com&gt;;
抄送:&nbsp;"5ab"<1729200611@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [oitl-5ab/OITL] 协议，版权，“参与开发”方面的一些问题 (#1)




我相信很多人都是没搞清楚 License 之间的区别及具体作用就开始在 GitHub 上把自己一些东西开源，随便加个协议，就算真的有人违反协议也不会去追究（我自己以前也是这样）。只不过还是严谨一点好。如果你不想给自己的代码加太多限制，MIT License 是最宽松的，只要使用者提一句“我用的这个东西是在 MIT License 下发布的”，没有其它任何限制。
 
https://www.gnu.org/licenses/license-list.html 比较详细地列出了很多 License。

**Comment by ouuan** [comment]
代码一般不用 Creative Commons 系列协议。但 GitHub 其实是支持它们的，如果你去其它地方搞一份协议来，放 LICENSE 里面，会在 repo 里显示你的协议是 CC XXX，还会有类似其它协议的简要说明。

我一个 repo 的截图：

![image](https://user-images.githubusercontent.com/30581822/76144688-ee38b280-60bd-11ea-86c9-af9385d4bd1f.png)

![image](https://user-images.githubusercontent.com/30581822/76144694-f7c21a80-60bd-11ea-90e2-a55ad8d819a0.png)

**Comment by ouuan** [comment]
可以参考 https://github.com/santisoler/cc-licenses

**Comment by oitl-5ab** [comment]
谢谢大佬。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ouuan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月7日(星期六) 晚上9:53
收件人:&nbsp;"oitl-5ab/OITL"<OITL@noreply.github.com&gt;;
抄送:&nbsp;"5ab"<1729200611@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [oitl-5ab/OITL] 协议，版权，“参与开发”方面的一些问题 (#1)




代码一般不用 Creative Commons 系列协议。但 GitHub 其实是支持它们的，如果你去其它地方搞一份协议来，放 LICENSE 里面，会在 repo 里显示你的协议是 CC XXX，还会有类似其它协议的简要说明。
 
我一个 repo 的截图：

**Comment by ouuan** [comment]
把协议删了的话默认保留所有权利..所以还是得加个 MIT License 或者 Apache License。
